openapi: "3.0"
info:
  version: 1.0.0
  title: kakao-moneythrowing API documentation
  contact:
    name: Junyoung Park
    email: pk920207@gmail.com

paths:
  /throwing:
    post:
      summary: 뿌리기 생성
      operationId: createThrowing
      tags:
      - Throwing
      parameters:
      - name: X-USER-ID
        in: header
        schema:
          type: string
          format: uuid
        required: true
      - name: X-ROOM-ID
        in: header
        schema:
          type: string
          format: uuid
        required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateThrowingRequest'
      responses:
        '201':
          $ref: '#/components/responses/ThrowingCreated'

  /throwing/{token}/receive:
    put:
      summary: 뿌린 금액 받기
      operationId: receiveThrowing
      tags:
      - Throwing
      parameters:
      - name: X-USER-ID
        in: header
        schema:
          type: string
          format: uuid
        required: true
      - name: X-ROOM-ID
        in: header
        schema:
          type: string
          format: uuid
        required: true
      - name: token
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          $ref: '#/components/responses/ThrowingReceived'

components:
  schemas:
    CreateThrowingRequest:
      type: object
      properties:
        moneyAmount:
          type: integer
        peopleCount:
          type: integer
    ThrowingToken:
      type: object
      properties:
        token:
          type: string
    ThrowingAmount:
      type: object
      properties:
        amount:
          type: integer

  responses:
    ThrowingCreated:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ThrowingToken'
    ThrowingReceived:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ThrowingToken'